### ISSUE TITLE
PTT在一開始第0個Epoch時，訓練到1000/1076，發生了錯誤

### ISSUE THREAD

**Issue by DavidLanz** [foamliu/Chatbot#3]
[2019-03-29 08:31:14] Epoch: [0][900/1076]      Batch Time 0.131 (0.130)        Loss 5.7915 (6.3353)
[2019-03-29 08:31:27] Epoch: [0][1000/1076]     Batch Time 0.137 (0.130)        Loss 5.9046 (6.3002)

在一開始第0個Epoch時，訓練到1000/1076，發生了錯誤，n_totals為0，分母為0跳出例外。

Traceback (most recent call last):
  File "train.py", line 241, in <module>
    main()
  File "train.py", line 214, in main
    val_loss = validate(val_loader, encoder, decoder)
  File "train.py", line 139, in validate
    return sum(print_losses) / n_totals
ZeroDivisionError: division by zero

**Comment by tonytan1701** [comment]
最近在研究闲聊系统， @DavidLanz 你在4月份也在忙生成式闲聊系统吗？

1. 以上你发现的错误ZeroDivisionError: division by zero很有可能是因为语料库中有些语句不是tab分割，我已解决该问题。

2. 该Seq2seq模型和[这个](https://github.com/fancyerii/blog-codes/blob/master/chatbot/chatbot_tutorial.ipynb)几乎一致，我已使用了别的语料库含5w条聊天。

问题：得出来的结论是语料库质量是关键，不知道你使用了什么语料库？
